trigger:
  - main

variables:
  - name: Tag
    value: "$(Build.BuildNumber)"
  - name: Repository
    value: "davidullrich/mailgraph"

jobs:
- job: BuildAndPublish
  displayName: Build and Publish Image

  pool:
    vmImage: ubuntu-latest

  steps:
  - task: Docker@2
    displayName: Login
    inputs:
      command: login
      containerRegistry: DockerHubConnection

  - task: Docker@2
    displayName: Build Image
    inputs:
      command: build
      dockerfile: "$(Build.SourcesDirectory)/Dockerfile"
      repository: $(Repository)
      addBaseImageData: false
      addPipelineData: false
      tags: |
        $(Tag)
        latest
    env:
      DOCKER_BUILDKIT: 1
  
  - task: Docker@2
    displayName: Push Image
    inputs:
      command: push
      repository: $(Repository)
      tags: |
        $(Tag)
        latest
    
  - task: Docker@2
    displayName: Logout
    inputs:
      command: logout
      containerRegistry: DockerHubConnection
