services:
  mailgraph-test:
    image: mailgraph:test
    container_name: mailgraph-test
    hostname: mail.domain.com
    restart: unless-stopped
    environment:
      - MAILGRAPH_SERVER_HOSTNAME=mail.domain.com
    ports:
      - "8585:8080"
    volumes:
      - ./testdata/mail.log:/var/log/mail/mail.log:ro
      - ./testdata/rrd:/var/www/mailgraph/rrd
      - /etc/localtime:/etc/localtime:ro